### PR TITLE
Adding bash ported version of the script!

### PR DESCRIPTION
**Pull request by pr0zac**
Per the request in the README, heres a bash ported version!

### CODE REVIEW

**Comment by gennyble** [comment]
Thank you! It seems that the `lw` function isn't working correctly. I don't think the variable is carrying from one function run to the next like it did in fish. I'm not sure how to fix this. Would declaring the variable outside of the function solve the problem? My bash is rusty.

**Comment by pr0zac** [comment]
Yeah I found the same issue! Got it mostly fixed. Need to eat some dinner real fast though! Will finish cleaning it up in an hour or so!

**Comment by gennyble** [comment]
Cool, thanks! I think I found the problem, but if you have something then I'll wait for you. Thanks again and I hope your dinner was good!

**Comment by pr0zac** [comment]
Ok, think I fixed it! I ended up changing a bit of the logic in the bash version cause I was using this as an excuse to refresh my bash knowledge and my ADHD started going a little nuts playing with things. If you fixed it in a way that works better without changing things feel free to use your version instead.

**Comment by gennyble** [comment]
Forgot merging closed the PR.

I appreciate the pull request even for a silly little project like this!

**Pull request merged**
